import { Product } from "./models/Product.js";
import { Category } from "./models/Category.js";
import { logger } from "./lib/logger.js";

const categories = [
  {
    name: "Salwar Sets",
    slug: "salwar-sets",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&auto=format&fit=crop&q=80",
    description: "Beautiful salwar sets for everyday elegance",
  },
  {
    name: "Co-ord Sets",
    slug: "co-ord-sets",
    image: "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/0P4A9437_ff9cc9ad-2540-4cb1-8dd3-f996737ab067.jpg",
    description: "Matching co-ordinated sets for a complete look",
  },
  {
    name: "Kurtas",
    slug: "kurtas",
    image: "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/3_dfadca2e-e763-4afd-81ff-424018f34a74_2.webp",
    description: "Elegant kurtas in comfortable fabrics",
  },
  {
    name: "Maternity Wear",
    slug: "maternity-wear",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&auto=format&fit=crop&q=80",
    description: "Comfortable and stylish maternity wear for every stage",
  },
  {
    name: "Sarees",
    slug: "sarees",
    image: "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/Outfit_Inspiration_8_3a828eab-b172-494a-891a-0ba2acca3e5d.png",
    description: "Timeless sarees for every occasion",
  },
  {
    name: "Kids",
    slug: "kids",
    image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&auto=format&fit=crop&q=80",
    description: "Charming kidswear for your little ones",
  },
  {
    name: "Night Wear",
    slug: "night-wear",
    image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&auto=format&fit=crop&q=80",
    description: "Cozy and comfortable night wear",
  },
  {
    name: "Bottoms",
    slug: "bottoms",
    image: "https://images.unsplash.com/photo-1583396618422-70d0b73eac01?w=400&auto=format&fit=crop&q=80",
    description: "Versatile bottoms to pair with any top",
  },
];

const products = [
  {
    name: "Sabr Madder Set",
    slug: "sabr-madder-set",
    description: "A stunning co-ord set crafted in rich madder hues, perfect for festive occasions.",
    price: 5450,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/IMG_9196.webp",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: true,
    onSale: false,
    tags: ["madder", "ajrakh", "festive"],
  },
  {
    name: "Titly Kalamkari Set",
    slug: "titly-kalamkari-set",
    description: "A vibrant Kalamkari printed co-ord set inspired by butterflies.",
    price: 4750,
    originalPrice: 5050,
    discount: 6,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/LTS9214_1.webp",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: true,
    onSale: true,
    tags: ["kalamkari", "printed", "butterfly"],
  },
  {
    name: "Arz Black Modal Set",
    slug: "arz-black-modal-set",
    description: "Luxurious black modal silk kurta pant set with delicate embroidery.",
    price: 6950,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/1_f999a9fc-6bf5-4f62-893c-3f1f341d9e0e.webp",
    ],
    category: "kurta-pant-sets",
    fabric: "Modal Silk",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: true,
    onSale: false,
    tags: ["modal", "silk", "black", "elegant"],
  },
  {
    name: "Qala Ajrakh Co-ord Set",
    slug: "qala-ajrakh-co-ord-set",
    description: "Traditional Ajrakh block-printed co-ord set with geometric patterns.",
    price: 5450,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/DSCF5911.webp",
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/DSCF5738.jpg",
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/DSCF5791.jpg",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    featured: true,
    onSale: false,
    tags: ["ajrakh", "block-print", "geometric"],
  },
  {
    name: "Gulbagh Co-ord Set",
    slug: "gulbagh-co-ord-set",
    description: "Floral garden-inspired Bagru print co-ord set in earthy tones.",
    price: 4950,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/23-HWC03157.webp",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: true,
    onSale: false,
    tags: ["bagru", "floral", "earthy"],
  },
  {
    name: "Sifar Beige Ajrakh Co-ord Set",
    slug: "sifar-beige-ajrakh-co-ord-set",
    description: "Beige Ajrakh co-ord set with intricate hand-block printing in natural dyes.",
    price: 5250,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/0P4A7931.webp",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: false,
    tags: ["ajrakh", "beige", "natural-dye"],
  },
  {
    name: "Beige Ajrakh Chanderi Silk Dupatta",
    slug: "beige-ajrakh-chanderi-silk-dupatta",
    description: "Elegant Chanderi silk dupatta with traditional Ajrakh prints.",
    price: 2450,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/DSCF8235_ca376798-f45b-4fee-a781-91c7171311b0.webp",
    ],
    category: "dupattas",
    fabric: "Chanderi Silk",
    sizes: ["Free Size"],
    inStock: true,
    featured: true,
    onSale: false,
    tags: ["ajrakh", "chanderi", "silk", "dupatta"],
  },
  {
    name: "Karya Indigo Ajrakh Co-ord Set",
    slug: "karya-indigo-ajrakh-co-ord-set",
    description: "Deep indigo Ajrakh co-ord set with hand-block printed traditional motifs.",
    price: 5650,
    images: [
      "https://cdn.shopify.com/s/files/1/0397/7681/3213/files/DSCF8708.webp",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: true,
    onSale: false,
    tags: ["ajrakh", "indigo", "block-print"],
  },
  {
    name: "Varnam Beige Kalamkari Co-ord Set",
    slug: "varnam-beige-kalamkari-co-ord-set",
    description: "Beige Kalamkari co-ord set featuring hand-painted nature motifs.",
    price: 5450,
    images: [
      "https://entwinestore.com/cdn/shop/files/rn-image_picker_lib_temp_02460eaa-46ce-4d20-a7ee-f0bd52feb982.jpg",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: false,
    tags: ["kalamkari", "beige", "nature"],
  },
  {
    name: "Imroz Black Modal Silk Co-ord Set",
    slug: "imroz-black-modal-silk-co-ord-set",
    description: "Sophisticated black modal silk co-ord set with subtle texture.",
    price: 7950,
    originalPrice: 8950,
    discount: 11,
    images: [
      "https://entwinestore.com/cdn/shop/files/IMG-5943.jpg",
      "https://entwinestore.com/cdn/shop/files/IMG-5956.jpg",
    ],
    category: "co-ord-sets",
    fabric: "Modal Silk",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: true,
    tags: ["modal", "silk", "black"],
  },
  {
    name: "Taamara Madder Red Bagru Kurta",
    slug: "taamara-madder-red-bagru-kurta",
    description: "Vibrant madder red Bagru block-printed kurta with classic motifs.",
    price: 3450,
    images: [
      "https://entwinestore.com/cdn/shop/files/9A355272-C22B-4CFC-8CB8-A0DC127BF667.jpg",
    ],
    category: "kurtas",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: false,
    tags: ["bagru", "madder", "red", "kurta"],
  },
  {
    name: "Alam Kurta Pant Set",
    slug: "alam-kurta-pant-set",
    description: "Classic kurta pant set with elegant block-print detailing.",
    price: 5250,
    images: [
      "https://entwinestore.com/cdn/shop/files/DSC00563.jpg",
      "https://entwinestore.com/cdn/shop/files/DSC00579.jpg",
    ],
    category: "kurta-pant-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: false,
    tags: ["block-print", "classic"],
  },
  {
    name: "Savera Kalamkari Co-ord Set",
    slug: "savera-kalamkari-co-ord-set",
    description: "Dawn-inspired Kalamkari co-ord set in warm pastels.",
    price: 5450,
    images: [
      "https://entwinestore.com/cdn/shop/files/DSCF5660.jpg",
      "https://entwinestore.com/cdn/shop/files/DSCF5681.jpg",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: false,
    tags: ["kalamkari", "pastel", "floral"],
  },
  {
    name: "Laya Ikat Co-ord Set",
    slug: "laya-ikat-co-ord-set",
    description: "Contemporary Ikat woven co-ord set with geometric patterns.",
    price: 5250,
    originalPrice: 5850,
    discount: 10,
    images: [
      "https://entwinestore.com/cdn/shop/files/IMG-8908.jpg",
      "https://entwinestore.com/cdn/shop/files/IMG-8909.jpg",
    ],
    category: "co-ord-sets",
    fabric: "Ikat Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: true,
    tags: ["ikat", "woven", "geometric"],
  },
  {
    name: "Gamyam Madder Red Bagru Co-ord Set",
    slug: "gamyam-madder-red-bagru-co-ord-set",
    description: "Bold madder red Bagru block-printed co-ord set for the fearless.",
    price: 4650,
    images: [
      "https://entwinestore.com/cdn/shop/files/1E9E9C79-4F87-4F9D-9344-16D50AE1990D.jpg",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: false,
    tags: ["bagru", "madder", "red", "bold"],
  },
  {
    name: "Kshana Indigo Bagru Kalidaar Set",
    slug: "kshana-indigo-bagru-kalidaar-set",
    description: "Flared kalidaar silhouette in deep indigo Bagru print.",
    price: 5650,
    images: [
      "https://entwinestore.com/cdn/shop/files/2448DAA1-919C-4FE3-8AD7-DAD6DDE11898.jpg",
    ],
    category: "co-ord-sets",
    fabric: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    featured: false,
    onSale: false,
    tags: ["bagru", "indigo", "kalidaar", "flared"],
  },
];

export async function seedDatabase(): Promise<void> {
  const categoryCount = await Category.countDocuments();
  const productCount = await Product.countDocuments();

  if (categoryCount === 0) {
    await Category.insertMany(categories);
    logger.info(`Seeded ${categories.length} categories`);
  }

  if (productCount === 0) {
    await Product.insertMany(products);
    logger.info(`Seeded ${products.length} products`);
  }
}
